### ISSUE TITLE
Feat: Store editor's HTML value in a v-model

### ISSUE THREAD

**Issue by DaniZGit** [modbender/nuxt-tiptap-editor#13]
Hello!
As the title says, I think it would be great if we could bind the editor's value directly using v-model. For example:
```vue
<TiptapEditorContent v-model="value" :editor="editor" />
```
I do believe this could introduce some complexity, especially when ensuring the editor's state is properly synced with the model. Tho I think it could be a very neat option to have.

**Comment by modbender** [comment]
I think you have misunderstood how this package works. Tiptap officially a [Vue 3 package](https://tiptap.dev/docs/editor/getting-started/install/vue3). 

`nuxt-tiptap-editor` package uses the functionality of this official Vue 3 package to provide stuff like Auto import and other configurations all in one install to your Nuxt 3 project.

So you will have to take this up to their repository if you want additional features:
https://github.com/ueberdosis/tiptap

**Comment by shayr1** [comment]
I know this is marked as complete, but I did it adapting tiptap docs here: https://tiptap.dev/docs/editor/getting-started/install/nuxt#use-v-model-optional
