### ISSUE TITLE
Question about editor code as in README image

### ISSUE THREAD

**Issue by Achraf931** [modbender/nuxt-tiptap-editor#7]
Hello

Thank you for your work, I would like to know if there was an example of the code to have the same rendering as on the README image? With the drag handle and the magnifying glass

<img width="400" alt="68747470733a2f2f6173736574732d676c6f62616c2e776562736974652d66696c65732e636f6d2f3634356139616365636461326530353934666163363132362f3635363735646538633363396366666331613461346432365f656469746f722d6561786d706c652d706c616365686f6c6465722d702d38" src="https://github.com/modbender/nuxt-tiptap-editor/assets/45672435/12509669-d82b-4b1d-9e53-61a3928d4974">

Thanks

**Comment by modbender** [comment]
Sorry but the image is from official Tiptap preview. Since Tiptap is a headless editor the UI elements need to be implemented by you. 

The image simply represents how cool Tiptap can look with the appropriate UI and fully functional implementation.
